[package]
name = "littlebit"
version = "0.1.0"
authors = ["Anirudha Bose <anirudha.bose@ledger.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uint = "0.8.2"
